### ISSUE TITLE
Public Release Mega Ticket

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/netts#130]
These are the issues/items that need to be closed before-we-can or in-order-to do the initial public release:

## Before public release (critical)
- [x] Choose initial release version (I would suggest `0.1.0` as per the usual <https://semver.org/>) also see #25 and 
- [x] Choose a name, as per #118 and rename repo/poetry project/docs/etc.
- [x] Logo for docs page. See #78. 
- [x] Agree what Python versions and operating systems we support (and to what extent). See also #84.
- [x] Remove legacy/ folder from repo. See #79.
- [x] Remove legacy folder and figures in docs from repo history. See #138 
- [x] License. See #3.
- [x] Decide on PyPi classifiers as per #46.
- [x] Long form documentation (and somewhere to host it?). See #10,  #77 and #22.

## Critical features
- [x] Decide on the public API (perhaps just the SpeechGraph, Settings and Clients to begin with) and document, as per #80.
- [x] Swap all remaining `print` statements for logging ones (and add logging config to docs). See #82.
- [ ] Let people decide text to ignore https://github.com/alan-turing-institute/netts/issues/50
- [ ] Add tests for CLI commands. See #85.

## Once released
- [ ] Add tests on gihub to run on all Python versions and operating systems
- [ ] Do we need to modify the pre-commit GH action once we make the repo public? See <https://github.com/pre-commit/action#using-this-action-in-private-repositories>.
- [ ] Update code test coverage badge in README (can only be done once public).
- [ ] Desciption on PyPI does not show image correctly.
- [ ] Contribution guidelines. See #1.
